name: Android CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test app
        run: |
          ./gradlew assembleDebug -Pminify=true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-app ${{ steps.version.outputs.builddate }}
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/build/outputs/apk/debug/app-debug.apk
          asset_name: WaRevamp_debug_${{ github.sha }}.apk
          tag: pre-release-${{ github.sha }}